# Generated by Django 2.1.1 on 2019-07-29 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodstype',
            old_name='descriptions',
            new_name='description',
        ),
    ]
